version: 2

jobs:
  gc_old_ec2_instances:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip3 install awscli
      - run: sudo apt-get update && sudo apt-get install jq
      - run: scripts/gc-ec2-instances.sh

  linux-custom-ami:
    docker:
      - image: hashicorp/packer:1.4.5
    steps:
      - checkout
      - run: apk update
      - run: apk add --no-progress python3 curl jq
      - run: pip3 install awscli pyyaml
      - run:
          name: Convert packer.yaml to packer.json
          command: |
            cat ./packer.yaml \
              | python3 -c 'import sys, yaml, json; y=yaml.safe_load(sys.stdin.read()); print(json.dumps(y))' \
              > ./packer.json
      - run:
          command: mkdir -p /tmp/results /tmp/artifacts
      - run:
          name: Build images
          no_output_timeout: 120m
          environment:
            # The AMI can take a very long time to be ready. These env
            # vars make packer wait 2 hours for this to happen before
            # giving up.
            AWS_MAX_ATTEMPTS: 120
            AWS_POLL_DELAY_SECONDS: 60
          command: |
            MONOREPO_CONTENT_SHA="$(sha256sum packer.yaml | cut -d " " -f 1)"
            [[ $CIRCLE_BRANCH != master ]] && IMAGE_FAMILY_SUFFIX="-dev"

            WINDOWS_USER="Administrator"

            ./scripts/get_last_image amazon-ebs "${MONOREPO_CONTENT_SHA}" "${CIRCLE_JOB}" "${AWS_DEFAULT_REGION}" && {
                echo "amazon-ebs image with monorepo_content_sha = ${MONOREPO_CONTENT_SHA} and circle_job_name = ${CIRCLE_JOB} already exists. Skipping build"
              } || packer build \
              -machine-readable \
              --only amazon-ebs \
              --var monorepo_content_sha="${MONOREPO_CONTENT_SHA}" \
              --var image_family_suffix="${IMAGE_FAMILY_SUFFIX}" \
              --var ami_region="${AWS_DEFAULT_REGION}" \
              --var windows_user="${WINDOWS_USER}" \
              --var test_results_path="/tmp/results/test-results.xml" \
              ${SOURCE_IMAGE_VAR} \
              ./packer.json | tee /tmp/artifacts/amazon-ebs-build.log
      - run:
          name: Summarize results
          command: |
            BUILD_LOG_PATH="/tmp/artifacts/amazon-ebs-build.log"
            if [[ -f $BUILD_LOG_PATH ]]; then
              IMAGE_NAME=$(grep 'artifact,0,id' "${BUILD_LOG_PATH}" | cut -d, -f6 | cut -d: -f2 || echo '')
              echo Recording just-built image $IMAGE_NAME as the output of this job
            else
              MONOREPO_CONTENT_SHA="$(sha256sum packer.yaml | cut -d " " -f 1)"

              IMAGE_NAME=$(./scripts/get_last_image amazon-ebs "${MONOREPO_CONTENT_SHA}" "${CIRCLE_JOB}" "${AWS_DEFAULT_REGION}")
              echo Nothing to build, recording previously-built image $IMAGE_NAME as the output of this job
            fi

            echo "Image ${IMAGE_NAME} is the latest image with content SHA ${MONOREPO_CONTENT_SHA}."
            echo $IMAGE_NAME > /tmp/artifacts/image-name.txt
      - run:
          name: Save test results if there are any
          command: |
            if [[ -f /tmp/results/test-results.xml ]]; then
              cp /tmp/results/test-results.xml /tmp/artifacts
            fi

      - store_test_results:
          path: /tmp/results

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2

  build_all_images:
    jobs:
      - linux-custom-ami

  daily:
    jobs:
      - gc_old_ec2_instances
    triggers:
      - schedule:
          cron: "17 12 * * *"
          filters:
            branches:
              only:
                - master
